---
blank_issues_enabled: false
contact_links:
    - name: 💬 GitHub Discussions
      url: https://github.com/TrueTickets/api-aggregator/discussions
      about: Ask questions, share ideas, and discuss with the community
    - name: 📚 Documentation
      url: https://github.com/TrueTickets/api-aggregator/blob/main/README.md
      about: Check the documentation for configuration and usage examples
    - name: 🔒 Security Issues
      url: https://github.com/TrueTickets/api-aggregator/security/advisories/new
      about: Report security vulnerabilities privately
