---
name: ✨ Feature Request
description: Suggest a new feature or enhancement for the API Aggregator
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

    - type: textarea
      id: problem
      attributes:
          label: Problem Statement
          description:
              What problem does this feature solve? What use case are you trying
              to address?
          placeholder: |
              Describe the problem you're trying to solve or the use case you're trying to address.
              For example: "I'm trying to aggregate data from APIs that require different authentication methods..."
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Proposed Solution
          description: What would you like to see implemented?
          placeholder: |
              Describe your proposed solution in detail. For example:
              - New configuration options
              - New transformation capabilities
              - New endpoints or functionality
              - Changes to existing behavior
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternative Solutions
          description: Have you considered any alternative approaches?
          placeholder: |
              Describe any alternative solutions or workarounds you've considered.
              This helps us understand the broader context of your request.

    - type: textarea
      id: configuration
      attributes:
          label: Configuration Example
          description:
              If applicable, show what the configuration might look like
          placeholder: |
              ```yaml
              # Example configuration for your proposed feature
              timeout: 10s
              endpoints:
                - endpoint: "/example"
                  new_feature:
                    option: value
              ```
          render: yaml

    - type: textarea
      id: api_example
      attributes:
          label: API Usage Example
          description: If applicable, show how the feature would be used
          placeholder: |
              ```bash
              # Example API calls or usage
              curl -X GET "http://localhost:8080/example" \
                -H "Content-Type: application/json"
              ```
          render: bash

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: How important is this feature to you?
          options:
              - Low - Nice to have
              - Medium - Would be helpful
              - High - Important for my use case
              - Critical - Blocking my use case
      validations:
          required: true

    - type: dropdown
      id: complexity
      attributes:
          label: Estimated Complexity
          description:
              How complex do you think this feature might be to implement?
          options:
              - Simple - Small configuration change
              - Medium - New functionality, moderate changes
              - Complex - Major feature, significant changes
              - Unknown - Not sure about complexity
      validations:
          required: true

    - type: textarea
      id: impact
      attributes:
          label: Impact Assessment
          description: What would be the impact of this feature?
          placeholder: |
              Consider:
              - Performance implications
              - Backward compatibility
              - Breaking changes
              - Documentation needs
              - Testing requirements

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: Any other context, screenshots, or examples
          placeholder: |
              Add any other context, links to documentation, examples from other tools,
              or any other information that might be helpful.

    - type: checkboxes
      id: terms
      attributes:
          label: Checklist
          description: Please confirm the following
          options:
              - label: I have searched existing issues to avoid duplicates
                required: true
              - label: I have provided a clear problem statement and solution
                required: true
              - label: I understand this is a feature request, not a bug report
                required: true
              - label: I am willing to help test this feature when available
                required: false
